config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :destroy, :create]
  resources :bands do
    # resources :albums, except: [:edit] do
    resources :albums, only: [:create, :destroy, :new, :update] do
      resources :tracks, only: [:create, :destroy, :new, :update]
    end
  end

  resources :albums, only: [:edit, :show, :index]
  resources :tracks, only: [:edit, :show, :index]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id      :integer          not null, primary key
#  title   :string           not null
#  year    :integer          not null
#  studio  :boolean          default(TRUE), not null
#  band_id :integer
#

class Album < ApplicationRecord

  validates :title, presence: true
  validates :title, presence: true
  validates :year, presence: true
  validates :band_id, presence: true

  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band

  has_many :tracks,
    foreign_key: :album_id,
    class_name: :Track

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id   :integer          not null, primary key
#  name :string           not null
#

class Band < ApplicationRecord

  validates :name, presence: true

  has_many :albums,
    foreign_key: :album_id,
    class_name: :Album

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id       :integer          not null, primary key
#  title    :string
#  ord      :integer
#  lyrics   :text
#  bonus    :boolean          default(FALSE)
#  album_id :integer
#

class Track < ApplicationRecord

  validates :title, presence: true
  validates :album_id, presence: true

  belongs_to :album,
   foreign_key: :album_id,
   class_name: :Album

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: {message: 'Password can\'t be blank'}
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  before_validation :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    if user
      return user if user.is_password?(password)
    else
      return nil
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
    if album_params[:studio] == "true"
      album_params[:studio] = true
    else
      album_params[:studio] = false
    end
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def new
    @band_id = params[:band_id].to_i
    @album = Album.new
    render :new
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def index
    @albums = Album.all
    render :index
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    # album = Album.find(params[:id])
    # album.name = params[:album][:name]
    # if album.save
    #   redirect_to album_url(album)
    # else
    #   render :edit
    # end
  end

  def destroy

  end

  def album_params
    params.require(:album).permit(:title, :year, :studio, :band_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?
  helper_method :logout_user!

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def create
    band = Band.new(band_params)

    if band.save
      redirect_to band_url(band)
    else
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def index
    @bands = Band.all
    render :index
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    band = Band.find(params[:id])
    band.name = params[:band][:name]
    if band.save
      redirect_to band_url(band)
    else
      render :edit
    end
  end

  def destroy

  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_user!
    redirect_to users_url
  end

  def new
    render :new
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @album_id = params[:album_id].to_i
    render :new
  end

  def index

  end

  def create
    if track_params[:bonus] = "true"
      track_params[:bonus] = true
    else
      track_params[:bonus] = false
    end

    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit

  end

  def track_params
    params.require(:track).permit(:title, :ord, :lyrics, :bonus, :album_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    render :index
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'>".html_safe
  end
end

app/views/albums/new.html.erb
<h1> Create a new Album </h1>
<form action="<%= band_albums_url %>" method="post">
  <%= auth_token %>
  <label for="title"> Please enter the title of the album
    <input type="text" name="album[title]" id="title">
  </label>
  <br>
  <label for="year"> year of this album
    <input type="text" name="album[year]" id="year">
  </label>
  <br>
  <label for="studio"> live or studio
    <br>
    <input type="radio" name="album[studio]" value="false" id="studio">live<br>
    <input type="radio" name="album[studio]" value="true" id="studio" checked>studio<br>
  </label>
  <input type="hidden" name="album[band_id]" value="<%=@band_id%>">
  <br>
  <input type="submit">
</form>

app/views/albums/show.html.erb
<h1> <%= @album.title %> </h>
  <h3> <%= @album.year %> </h3>

app/views/bands/edit.html.erb
<h1> Please edit bands name </h1>
<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label for="name"> Please enter name of the band
    <input type="text" name="band[name]" id="name" value="<%= @band.name %>">
  </label>
  <input type="submit">
</form>

app/views/bands/index.html.erb
  <h1> This is all of our bands <h1>
    <% @bands.each do |band| %>
    <p><%= band.name %><p>
      <br>
    <% end %>

app/views/bands/new.html.erb
<h1> Create a new band </h1>
<form action="<%= bands_url %>" method="post">
  <%= auth_token %>
  <label for="name"> Please enter name of the band
    <input type="text" name="band[name]" id="name">
  </label>
  <input type="submit">
</form>

app/views/bands/show.html.erb
<br>
<p1> This is a <%= @band.name %> page <p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <h1 class="main-logo">My Music App</h1>
    <% if current_user %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete"
        <%= auth_token %>
        <input type="submit" value='logout'>
      </form>
    <% else %>
      <form action="<%= new_session_url %>" method="get">
        <%= auth_token %>
        <input type="submit" value='login'>
      </form>
    <% end %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tracks/new.html.erb
<h1> Create a new track </h1>
<form action="<%= band_album_tracks_url %>" method="post">
  <%= auth_token %>
  <label for="title"> Please enter the title of the track
    <input type="text" name="track[title]" id="title">
  </label>
  <br>
  <label for="ord"> Please enter number of the track on the album
    <input type="integer" name="track[ord]" id="ord">
  </label>
  <br>
  <input type="hidden" name="track[album_id]" value="<%=@album_id%>">
  <br>
  <input type="submit">
</form>

app/views/tracks/show.html.erb
<h1> <%= @track.title %> </h>
  <h3> <%= @track.ord %> </h3>

app/views/users/index.html.erb
<p3> Hello login or sign up <p3>
  <br>
  <form action="<%= new_user_url %>" method="get">
    <input type="submit" value='sign up'>
  </form>

app/views/users/new.html.erb
<h1> Create a new user </h1>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="email"> Please enter your email
    <input type="text" name="user[email]" id="email">
  </label>
  <br>
  <label for="password"> Please enter your password
    <input type="password" name="user[password]" id="password">
  </label>
  <br>
  <input type="submit">
</form>

app/views/users/show.html.erb
<h1> Hello <%= @user.email %> </h>